-- 留言点赞：message_id + 指纹去重（同一访客对同一条留言只计一次）
CREATE TABLE message_likes (
    message_id BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    fingerprint VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (message_id, fingerprint)
);
CREATE INDEX idx_message_likes_message ON message_likes(message_id);

-- 留言评论
CREATE TABLE message_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    name VARCHAR(80) NOT NULL,
    content VARCHAR(500) NOT NULL,
    is_author BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_message_comments_message ON message_comments(message_id, created_at);
