-- 学习记录板块：学习进度 + 学习日志
-- 学习进度：与 learning_resources 一一对应，记录每篇教程的学习状态
CREATE TABLE learning_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_id BIGINT NOT NULL REFERENCES learning_resources(id) ON DELETE CASCADE UNIQUE,
    status VARCHAR(20) NOT NULL DEFAULT 'NOT_STARTED',
    note TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_learning_progress_status ON learning_progress(status);

-- 学习日志：按时间记录的学习过程（学了什么、踩了什么坑、完成了什么）
CREATE TABLE learning_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_date DATE NOT NULL,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    tags TEXT NOT NULL DEFAULT '[]',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_learning_logs_date ON learning_logs(log_date DESC, id DESC);

-- 把已有的学习资源全部初始化为「未开始」进度
INSERT INTO learning_progress(resource_id, status, sort_order)
SELECT id, 'NOT_STARTED', sort_order FROM learning_resources;
