CREATE TABLE article_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    slug VARCHAR(180) NOT NULL,
    title VARCHAR(160) NOT NULL,
    excerpt VARCHAR(320) NOT NULL,
    category VARCHAR(80) NOT NULL,
    tags TEXT NOT NULL,
    content TEXT NOT NULL,
    status VARCHAR(20) NOT NULL,
    reading_minutes INTEGER NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_article_versions_article_date ON article_versions(article_id, created_at DESC, id DESC);

INSERT INTO article_versions(article_id,slug,title,excerpt,category,tags,content,status,reading_minutes,published_at)
SELECT id,slug,title,excerpt,category,tags,content,status,reading_minutes,published_at FROM articles;
