CREATE TABLE game_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(180) NOT NULL UNIQUE,
    title VARCHAR(200) NOT NULL,
    cover_url VARCHAR(1000),
    platform VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL,
    score NUMERIC(3,1),
    hours_played INTEGER NOT NULL DEFAULT 0,
    completed_on DATE,
    verdict VARCHAR(1000) NOT NULL,
    review_article_slug VARCHAR(180),
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_game_status CHECK (status IN ('PLAYING','COMPLETED','WISHLIST','DROPPED')),
    CONSTRAINT chk_game_score CHECK (score IS NULL OR (score >= 0 AND score <= 10)),
    CONSTRAINT chk_game_hours CHECK (hours_played >= 0)
);

CREATE INDEX idx_game_entries_status_sort ON game_entries(status, sort_order, id);
